set dotenv-load

migrate *args:
    migrate \
        -source file://migration \
        -database "pgx5://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}" \
        -verbose {{args}}

go-dev *args:
    air -c .air.toml {{args}}

js-dev *args: 
    cd js && pnpm i && pnpm run dev {{args}}

dev:
    npm i -g concurrently && concurrently "just go-dev" "just js-dev"